Form/DataField/PasswordFieldType.php
- add viewTransform and reverseViewTransform
- remove duplication of password label
- add bcrypt algorithm with a default cost of 12
=> Fix password type

Resources/views/data/edit-revision.html.twig
- Uncaught ReferenceError: ckconfig is not defined
=> fix ckconfig is not defined

Resources/public/css/styles.css, Resources/public/js/app.js, Resources/sass/_ems.scss, Resources/views/form/fields.html.twig, Resources/views/macros/data-field-type.html.twig
=> issue-40 collapsible collection

Command/RecomputeCommand.php, Service/DataService.php
=> Bugfix: sign data during rebuild

Resources/views/data/edit-revision.html.twig
Bug because we changed the title for including the content type icon:
https://github.com/ems-project/EMSCoreBundle/commit/974fe193d2bde1e2d09d7a9b4c75ef848bae69bb
=> bugfix: select2 sortable not working

Controller/AppController.php, Controller/ContentManagement/ContentTypeController.php, Controller/ContentManagement/DataController.php, Controller/ElasticsearchController.php, Controller/SearchController.php, Controller/Views/CriteriaController.php, Controller/WysiwygController.php, Service/AssetExtratorService.php, Tika/TikaWrapper.php, composer.json
- remove symfony/symfony define packages
- remove tika dependency
=> Upgrade: symfony 4.1

Resources/views/elements/side-menu.html.twig
=> issue38: firefox side menu icon bug

Twig/AppExtension.php
=> Asset links are treated separately from the ems:object links 

Command/MigrateCommand.php, Elasticsearch/Bulker.php, Resources/config/services.yml
The common bundle should not contain the elasticsearch bulker class.
Because the clientHelperBundle will never bulk documents to
elasticsearch.
=> task: move back the bulker from common

Controller/ContentManagement/DataController.php, Form/Form/CompareEnvironmentFormType.php, Resources/views/data/revisions-data.html.twig, Resources/views/form/fields.html.twig, Resources/views/macros/data-field-type.html.twig, Twig/AppExtension.php
Limit referrers at the bottom of a revision to the default environment of the current revision
Fixes #49 index start at 1 on revision display
Hide technical data in data-ems-id attribute, unless you are super user.
=> User improvements

.gitignore, Controller/ElasticsearchController.php, Entity/AggregateOption.php, Entity/Form/SearchFilter.php, Form/DataField/IntegerFieldType.php, Resources/config/services.yml, Resources/views/elasticsearch/search.html.twig, Service/Mapping.php, Service/SearchService.php
1) IntegerField type add mapping option copy_to
=> Feature requests

Elasticsearch/Bulker.php, Elasticsearch/Indexer.php, Resources/config/services.yml
https://github.com/elastic/elasticsearch-php/issues/225
=> bugfix: bulker connection timeout after 5 min

Controller/ContentManagement/EnvironmentController.php, Resources/views/environment/index.html.twig
…ach alias with multiple indexes
=> Attach multiple indexes and/or manage aliases as external environment

Twig/AppExtension.php
The twig data filter should do a elasticsearch search instead of a get
call. Multiple indexes get will not work!
=> bugfix: twig data filter search instead of get

Elasticsearch/Indexer.php
Used in the append option for import
=> Added getAliases to indexer

Entity/FieldType.php, Form/FieldType/FieldTypeType.php
Avoid not required datafieldtype option when  an option is removed
=> filter Display Options

Controller/ContentManagement/FileController.php, Service/AssetExtractorService.php, Service/RestClientService.php
Adjust the request timeout on forced request + save the session to avoid to block the user
=> Better asset extractor

Command/AlignCommand.php, ContentTransformer/ContentTransformContext.php, ContentTransformer/ContentTransformInterface.php, ContentTransformer/HtmlStylesRemover.php, Service/TransformContentTypeService.php
Some changes after test in local for the HIPPOC project
=> Feature / Content transformer workflow refactoring

Controller/ContentManagement/DataController.php, Controller/NotificationController.php, Repository/RevisionRepository.php, Resources/config/services.yml, Service/DataService.php, Service/RevisionService.php, Twig/RevisionRuntime.php
- Remove function findIdByOuuidAndContentTypeAndEnvironment for
duplication use findByOuuidAndContentTypeAndEnvironment
=> Bugfix typpo environnement -> environment

Resources/views/macros/data-field-type.html.twig
interactive nested list instead of JSON ACE viewer
=> Better display for JSON menu in revision

Command/RevisionCopyCommand.php, Controller/ContentManagement/DataController.php, Service/Revision/Copy/CopyContext.php, Service/Revision/Copy/CopyService.php
Sorry forgot this in my previous PR :(
=> Add merge option for copy command

Command/RevisionCopyCommand.php, Controller/AppController.php, Controller/ContentManagement/IndexController.php, Controller/ContentManagement/NatureController.php, Controller/ContentManagement/PublishController.php, Controller/ElasticsearchController.php, Controller/Views/CalendarController.php, Controller/Views/CriteriaController.php, Controller/Views/HierarchicalController.php, Resources/config/services.yml, Resources/views/elasticsearch/status.html.twig, Service/ElasticsearchService.php, Service/Revision/Copy/CopyContext.php, Service/Revision/Copy/CopyService.php, Service/Revision/RevisionService.php, composer.json
|Bug fix?       |no|
|New feature?   |yes|	
|BC breaks?     |no|	
|Deprecations?  |no|	
|Fixed tickets  |no|	
The goal of this PR is using a new elasticsearch client from the common. All dependencies to the real elasticsearch library should be removed. **Important this PR will not break anything**!
The new client development on the commonBundle: 
https://github.com/ems-project/EMSCommonBundle/pull/74/files
=> feat(es7): using new elasticsearch client

Controller/ContentManagement/PublishController.php
There is another PR to take care of this (using a command), but this one is the hotfix version (to be merged ASAP with the master branch)
=> Hotfix, missing body in publish request

Controller/ContentManagement/CrudController.php
=> hot: fix a misformatted annotation

Controller/Api/FormSubmissionController.php, DependencyInjection/EMSCoreExtension.php, Entity/FormSubmission.php, Entity/FormSubmissionFile.php, Resources/DoctrineMigrations/pdo_mysql/Version20200714084508.php, Resources/DoctrineMigrations/pdo_pgsql/Version20200714111326.php, Resources/DoctrineMigrations/pdo_sqlite/Version20200714084731.php, Resources/config/services.yml, Service/FormSubmission/FormSubmissionException.php, Service/FormSubmission/FormSubmissionService.php, Service/FormSubmission/SubmitRequest.php, composer.json, phpstan-baseline.neon
|Bug fix?       |no|
|New feature?   |yes|	
|BC breaks?     |no|	
|Deprecations?  |no|	
|Fixed tickets  |no|	
Api form submission
=> feat: api form submission

Controller/ContentManagement/ContentTypeController.php, Entity/Form/ContentTypeJsonUpdate.php, Entity/FormSubmission.php, Entity/Helper/JsonClass.php, Form/Form/ContentTypeUpdateType.php, Resources/DoctrineMigrations/pdo_mysql/Version20200714084508.php, Resources/DoctrineMigrations/pdo_mysql/Version20200720135039.php, Resources/DoctrineMigrations/pdo_pgsql/Version20200714111326.php, Resources/DoctrineMigrations/pdo_pgsql/Version20200720134850.php, Resources/DoctrineMigrations/pdo_sqlite/Version20200720135153.php, Resources/translations/EMSCoreBundle.en.yml, Resources/views/contenttype/edit.html.twig, Resources/views/contenttype/json_update.html.twig, Service/ContentTypeService.php
Feat/submission process fields and form to update a content type from a json file
|New feature?   |Y0|	
* feat(contenttype): form to update a content type definition from a json file
* feat:submission fields
=> feat: submission process fields and form to update a content type from a json file

Controller/Form/SubmissionController.php, Entity/FormSubmission.php, Entity/FormSubmissionFile.php, Form/Submission/ProcessType.php, Repository/FormSubmissionRepository.php, Resources/DoctrineMigrations/pdo_mysql/Version20200901071708.php, Resources/DoctrineMigrations/pdo_pgsql/Version20200901053756.php, Resources/DoctrineMigrations/pdo_sqlite/Version20200901072344.php, Resources/config/services.yml, Resources/translations/EMSCoreBundle.en.yml, Resources/views/elements/side-menu.html.twig, Resources/views/submission/overview.html.twig, Service/Form/Submission/FormSubmissionService.php
|Bug fix?       |no|
|New feature?   |yes|	
|BC breaks?     |no|	
|Deprecations?  |no|	
|Fixed tickets  |no|	
feat: UI form submissions:
The user should be able to process form submissions
The user should be able to download form submissions (before processing)
Add new field "process_by"
Add new role "ROLE_FORM_CRM"
=> Release 1.13.12

Entity/AuthToken.php, Entity/User.php, Service/UserService.php, phpstan-baseline.neon
=> Fix: Doctrine AuthToken to User relation error

Controller/ContentManagement/FileController.php
=> Release 1.13.14

Entity/FormSubmission.php, Resources/DoctrineMigrations/pdo_mysql/Version20200911073342.php, Resources/DoctrineMigrations/pdo_pgsql/Version20200911073341.php, Resources/DoctrineMigrations/pdo_sqlite/Version20200911091519.php, Resources/translations/EMSCoreBundle.en.yml, Resources/views/submission/overview.html.twig, Service/Form/Submission/FormSubmissionRequest.php, Service/Form/Submission/FormSubmissionService.php
|Bug fix?       |No|
|New feature?   |Yes|	
|BC breaks?     |No|	
|Deprecations?  |No|	
|Fixed tickets  |Yes|	
Added a dynamic label and deadline date field, allowed i18n of Process button and form.
=> feat: Label and deadline date for form submissions

Controller/ContentManagement/CrudController.php, Entity/FormSubmission.php, Resources/DoctrineMigrations/pdo_mysql/Version20200911073342.php, Resources/DoctrineMigrations/pdo_pgsql/Version20200911073341.php, Resources/DoctrineMigrations/pdo_sqlite/Version20200911091519.php, Resources/translations/EMSCoreBundle.en.yml, Resources/views/submission/overview.html.twig, Service/Form/Submission/FormSubmissionRequest.php, Service/UserService.php
feat: Label and deadline date for form submissions (#397)
feat(role): add a role read-only for users list (#396)
=> Release 1.13.16

Controller/ContentManagement/FileController.php, Resources/config/services.yml, Service/FileService.php
=> fix: Reactivate simple asset urls

Controller/TwigElementsController.php, Service/Mapping.php, phpstan-baseline.neon
=> WIP: Migrate to elastica

Command/ExtractAssetCommand.php, Controller/ContentManagement/FileController.php, Service/AssetExtractorService.php
=> chore: missing \

Resources/DoctrineMigrations/pdo_mysql/Version20200921075641.php, Resources/DoctrineMigrations/pdo_pgsql/Version20200921075641.php, Resources/DoctrineMigrations/pdo_sqlite/Version20200921080015.php
=> fix(doctrine): not existing expire_date

Exception/CantBeFinalizedException.php, Form/Field/ObjectChoiceLoader.php, Resources/config/services.yml, Service/ContentTypeService.php, Service/Form/Verification/FormVerificationException.php, Service/ObjectChoiceCacheService.php, Twig/AppExtension.php, phpstan-baseline.neon
- chore: ObjectChoiceCacheService phpstan issues
- refact: Use Common Document to parse hit result
- refact: Load list is using elastica
- chore: typo in var name
- refact: client migrated to elastica
=> fix: object choice loader (#436)

composer.json, phpstan-baseline.neon, src/Command/ReindexCommand.php, src/Controller/ElasticsearchController.php, src/DependencyInjection/Configuration.php, src/DependencyInjection/EMSCoreExtension.php, src/Resources/config/services.yml, src/Resources/translations/EMSCoreBundle.en.yml, src/Resources/views/elasticsearch/search.html.twig, src/Service/AggregateOptionService.php, src/Service/ContentTypeService.php, src/Service/DataService.php, src/Service/ElasticsearchService.php, src/Service/EntityService.php, src/Service/EnvironmentService.php, src/Service/Mapping.php, src/Service/ObjectChoiceCacheService.php, src/Service/SearchService.php, src/Twig/AppExtension.php
The idea of this PR is bright es6 and es7 support with a es5 client. In order to have a bridge version to migrate all projets to a ES7 without bing bang
=> WIP:Feat/es6, es7 support and elastica migration

phpstan-baseline.neon, src/Controller/ContentManagement/ContentTypeController.php, src/Controller/ContentManagement/DataController.php, src/Controller/ContentManagement/EnvironmentController.php, src/Controller/ContentManagement/ManagedAliasController.php, src/Controller/ElasticsearchController.php, src/Controller/I18nController.php, src/Controller/UserController.php, src/DependencyInjection/EMSCoreExtension.php, src/Elasticsearch/Index/Mappings.php, src/Elasticsearch/Index/Settings.php, src/Entity/AuthToken.php, src/Entity/ContentType.php, src/Entity/DataField.php, src/Entity/FieldType.php, src/Entity/Helper/JsonDeserializer.php, src/Entity/Template.php, src/Service/DataService.php
|Bug fix?       |Yes|
|New feature?   |No|	
|BC breaks?     |No|	
|Deprecations?  |No|	
|Fixed tickets  |No|	
Mainly typehint fixes
=> WIP: Legacy code phpstan fixes

composer.json
Travis was broken due to new dependencies imposed by dev-master of rector/rector
=> bug: use fixed version for rector

src/Controller/ContentManagement/DataController.php
=> fix: debug reorderCollection method after phpstan cleaning

src/Twig/AppExtension.php
=> feat: new emsco_uuid twig filter

src/Twig/AppExtension.php
=> fix: data filter on null key

src/Controller/Revision/JsonMenuNestedController.php, src/Core/Revision/RawDataTransformer.php, src/Entity/Revision.php
Remove virtual fields from json menu nested containers/modals
=> fix: virtual fields in json menu nested

src/Controller/ContentManagement/DataController.php
Broken in this commit: https://github.com/ems-project/EMSCoreBundle/commit/f991972905ed4398e18797a20574f41457c20f4f
=> fix: allow new-draft from get request

src/Controller/ContentManagement/DataController.php, src/Controller/Revision/JsonMenuNestedController.php, src/Core/Revision/RawDataTransformer.php, src/Entity/Revision.php, src/Twig/AppExtension.php
- fix: data filter on null key
- fix: virtual fields in json menu nested
- fix: allow new-draft from get request
=> Release 1.14.7

src/Controller/ContentManagement/DataController.php, src/Service/IndexService.php
=> ref: migrate DataController.php

src/Form/View/SorterViewType.php
=> fix: environment name not alias

src/Controller/ElasticsearchController.php, src/Entity/Form/Search.php, src/Form/View/SorterViewType.php, src/Service/SearchService.php
Resolved db and es query issues
=> fix: datalink search broken

src/Controller/ElasticsearchController.php, src/Entity/Form/Search.php, src/Form/View/SorterViewType.php, src/Service/SearchService.php
=> Released 1.14.12

src/Service/DataService.php
=> fix: _contenttype missing in revision

src/Service/DataService.php
|BC breaks?     |Y|	
|Fixed tickets  |Y|
=> fix: avoid warning message on probably not-yet-indexed content

src/Controller/ContentManagement/DataController.php, src/Controller/ContentManagement/EnvironmentController.php, src/Controller/ElasticsearchController.php, src/Service/DataService.php
=> fix Missing404Exception replaced by NotFoundException

src/DependencyInjection/Configuration.php, src/DependencyInjection/EMSCoreExtension.php, src/Resources/config/services.yml, src/Service/DataService.php
=> feat: pre generated ouuids

src/Entity/ContentType.php, src/Entity/FieldType.php, src/Entity/Helper/JsonDeserializer.php, src/Entity/Template.php
=> fix: mixed object not array

src/Controller/ContentManagement/EnvironmentController.php
=> fix: build alias/index informations

src/Entity/AuthToken.php, src/Entity/DataField.php, src/Entity/Environment.php, src/Entity/FieldType.php, src/Entity/Form/SearchFilter.php, src/Entity/Notification.php, src/Entity/Revision.php, src/Entity/Template.php, src/Entity/User.php, src/Entity/UserInterface.php, src/Entity/View.php, src/Form/View/ImporterViewType.php, src/Service/DataService.php
=> chore: new php cs

src/Controller/UserController.php, src/DependencyInjection/EMSCoreExtension.php, src/Entity/AuthToken.php, src/Entity/DataField.php, src/Entity/Environment.php, src/Entity/FieldType.php, src/Entity/Form/SearchFilter.php, src/Entity/Notification.php, src/Entity/Revision.php, src/Entity/Template.php, src/Entity/User.php, src/Entity/UserInterface.php, src/Entity/View.php, src/Form/View/ImporterViewType.php, src/Resources/config/controllers.xml, src/Resources/config/services.yml, src/Service/AliasService.php, src/Service/DataService.php, src/Service/EnvironmentService.php, src/Service/UserService.php
* fix: empty index dot have result => 0 document
* remove silly comment
* chore: migrate controller services config to specific xml config
* fix: ems_core.circles_object passed by service attribute not dynamically
* fix: pass ems_core.instance_id from service constuctor
* simplified excluded autowired controllers
=> Release 1.14.18

src/Controller/ContentManagement/CrudController.php
=> feat: json routes for api calls

src/Service/Mapping.php, src/Service/SearchService.php
=> chore: moved to common

src/Entity/ContentType.php
SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column
"type" violates not-null constraint
=> fix: bug content type clean command

src/Entity/ContentType.php, src/Entity/Revision.php, src/Form/DataField/DataFieldType.php, src/Form/Form/EmsCollectionType.php
=> fix: _version_uuid missing in post processing

src/Entity/ContentType.php, src/Entity/Revision.php, src/Form/DataField/DataFieldType.php, src/Form/Form/EmsCollectionType.php
=> Release 1.14.22

src/EventListener/RequestListener.php
=> fix: empty channel attribute

src/EventListener/RequestListener.php, src/Form/Form/TableType.php, src/Resources/config/services.yml, src/Resources/translations/EMSCoreBundle.en.yml, src/Service/ChannelService.php
Take care of the emsch breaking changes
=> Fix/emsch 3.4

composer.json, src/EventListener/RequestListener.php, src/Form/Form/TableType.php, src/Resources/config/services.yml, src/Resources/translations/EMSCoreBundle.en.yml, src/Service/ChannelService.php
Forgot about the composer dependency to emsch 3.5
=> Fix/emsch 3.5

src/DependencyInjection/Configuration.php, src/DependencyInjection/EMSCoreExtension.php, src/Resources/config/services.yml
=> feat: option to define the log level or to disable it

composer.json, src/DependencyInjection/Configuration.php, src/DependencyInjection/EMSCoreExtension.php, src/Resources/config/services.yml
=> Release 1.14.30

src/Service/AliasService.php
=> fix: array of actions not array of actions in a array

src/Controller/ElasticsearchController.php, src/DependencyInjection/EMSCoreExtension.php, src/Resources/views/elasticsearch/search.json.twig
=> Hotfix: dataLink search, JsonMenuNested modals

src/Controller/ElasticsearchController.php, src/DependencyInjection/EMSCoreExtension.php, src/Resources/views/channel/index.html.twig, src/Resources/views/elasticsearch/search.json.twig, src/Resources/views/form/forms.html.twig
=> Release 1.14.34

src/Controller/ChannelController.php, src/DependencyInjection/EMSCoreExtension.php, src/Elasticsearch/Bulker.php, src/Entity/Channel.php, src/EventListener/RequestListener.php, src/Exception/NotFoundException.php, src/Form/Data/EntityTable.php, src/Form/Data/TableColumn.php, src/Form/DataTransformer/ChannelOptionsTransformer.php, src/Form/Subform/ChannelOptionsType.php, src/Repository/ChannelRepository.php, src/Resources/config/services.xml, src/Resources/config/services.yml, src/Resources/translations/EMSCoreBundle.en.yml, src/Resources/views/form/forms.html.twig, src/Service/Channel/ChannelRegistrar.php, src/Service/Channel/ChannelService.php, src/Twig/AppExtension.php
=> Support/client helper 3.6

src/Controller/ElasticsearchController.php, src/Resources/views/elasticsearch/status.html.twig
|BC breaks?     |Y|	
/admin/phpinfo has been removed/cleaned
=> refactor: remove phpinfo (duplicate with the symfony debug bar)

phpstan-baseline.neon, src/Command/RecomputeCommand.php, src/Controller/ContentManagement/DataController.php, src/Elasticsearch/Bulker.php, src/Form/DataField/CheckboxFieldType.php
=> fix: migration issue

phpstan-baseline.neon, src/Form/View/CriteriaViewType.php, src/Form/View/ImporterViewType.php
must be an instance of Symfony\Bundle\FrameworkBundle\Routing\Router, instance of Symfony\Cmf\Component\Routing\ChainRouter given
=> fix: inject RouterInterface

src/Resources/views/elasticsearch/search.json.twig
=> fix: regression icon has disappear from the data link drop down menu

assets/cke-plugins/adv_link/dialogs/link.js, assets/cke-plugins/adv_link/lang/en.js, assets/cke-plugins/adv_link/lang/fr.js, assets/cke-plugins/adv_link/lang/nl.js, assets/cke-plugins/adv_link/plugin.js, src/Resources/public/js/cke-plugins/adv_link/dialogs/link.js, src/Resources/public/js/cke-plugins/adv_link/lang/en.js, src/Resources/public/js/cke-plugins/adv_link/lang/fr.js, src/Resources/public/js/cke-plugins/adv_link/lang/nl.js, src/Resources/public/js/cke-plugins/adv_link/plugin.js
Add the option to directly create a link to a file (and upload it) in the wysiwyg
=> feat: add link to file in wysiwyg

.github/workflows/code_quality.yml, .php_cs.dist, phpstan-baseline.neon, phpstan.neon.dist, src-user/DependencyInjection/Compiler/ValidationPass.php
Activate github actions cfr maintainer bundle
=> chore: github actions

src/Form/DataField/SelectUserPropertyFieldType.php
=> fix: selectUserPropertyType add mapping

src/Service/Mapping.php
Version check for es7 was inversed
=> fix: _all field generation for es7

src/Service/Mapping.php
Nested fields should also be copied to the _all field
=> fix: nested copy_to _all field mapping

phpstan-baseline.neon, src/Controller/Revision/JsonMenuNestedController.php, src/Entity/Revision.php, src/Form/DataField/DataFieldType.php, src/Form/Form/RevisionJsonMenuNestedType.php, src/Resources/config/services.yml, src/Resources/views/data/json-menu-nested.html.twig, src/Service/DataService.php, src/Service/Revision/PostProcessingService.php
- Isolate post processing in new service
- Add giveContentType on Revision for not doing nullable checks on something that should not be null.
- If the nested container has a field called label, don't add a label.
=> Fix: post processing json menu nested

src/Controller/Revision/JsonMenuNestedController.php, src/Entity/FieldType.php, src/Form/Form/RevisionJsonMenuNestedType.php, src/Resources/views/data/json-menu-nested.html.twig, src/Service/Revision/PostProcessingService.php
=> fix: jsonMenuNested setLabel and edit layout

src/Controller/ElasticsearchController.php, src/Resources/views/elasticsearch/search.html.twig
Default Search in ES7 environment
=> fix: default search (#590)

src/Command/LockCommand.php, src/Resources/config/command.xml, src/Resources/config/services.yml, src/Resources/views/data/view-data.html.twig, src/Resources/views/view/custom/gallery_view.html.twig, src/Resources/views/view/custom/hierarchical_view.html.twig, src/Service/NotificationService.php
=> Release 1.14.46

src/Command/DeleteCommand.php, src/Command/LockCommand.php, src/Command/MigrateCommand.php, src/Command/RecomputeCommand.php, src/Service/AliasService.php
=> Release 1.14.47

src/Resources/views/view/custom/hierarchical_add_item.html.twig
=> fix: sorter view not collapsing

src/Core/Revision/RawDataTransformer.php
=> fix: rawDataTransformer isset call

src/Service/Revision/PostProcessingService.php
=> fix: post processing catch fatals

src/Command/ExportDocumentsCommand.php
Before:
/data/asset/17f3b06cbed8eb295fbc0aa4b532095256744fc5/processor/export.zip
After fix:
/data/asset/fc2a88f84537e9709fd2ab0512e05278525669b3/74eee8f000c25dc552dbef95a5cda95e59a9b16b/export.zip
=> fix: export docs cmd asset url

src/Command/Revision/TimeMachineCommand.php
=> fix: bug timemachine

src/Command/Revision/TimeMachineCommand.php, src/Form/DataField/ChoiceFieldType.php, src/Form/DataField/JsonMenuLinkFieldType.php, src/Form/DataField/JsonMenuNestedLinkFieldType.php, src/Form/DataField/SelectFieldType.php, src/Resources/views/elasticsearch/search.html.twig, src/Service/DataService.php
=> release 1.14.51

src/Twig/AppExtension.php
Notice: Undefined index: color
=> fix: php notices color field not defined

src/Twig/AppExtension.php
- php notices color field not defined (#621)
=> release: 1.14.52

LICENSE, composer.json
https://github.com/ems-project/maintainers/issues/15
=> chore: composer and license

.github/workflows/commit_quality.yml
https://github.com/ems-project/maintainers/issues/17
=> ci: Commit quality

src/Controller/Views/CriteriaController.php
=> chore: phpstan issues

src/Controller/UserController.php, src/Form/Data/TableColumn.php, src/Resources/views/form/forms.html.twig
#Fixes:
- Order on date column
- comma list without ugly space in entyti table
#Refactor
- Hide loop.index in non sortable data table view
#Feature:
- Header with a icon
=> refactor: user views

src/Controller/ChannelController.php, src/Controller/ContentManagement/ActionController.php, src/Controller/Form/SubmissionController.php, src/Controller/UploadedFileController.php, src/Controller/UserController.php, src/Form/Data/BoolTableColumn.php, src/Form/Data/BytesTableColumn.php, src/Form/Data/DataLinksTableColumn.php, src/Form/Data/DatetimeTableColumn.php, src/Form/Data/RolesTableColumn.php, src/Form/Data/TableAbstract.php, src/Form/Data/TableColumn.php, src/Form/Data/UserTableColumn.php, src/Resources/translations/EMSCoreBundle.en.yml, src/Resources/views/form/forms.html.twig
=> refactor: better table column

src/Service/Form/Submission/FormSubmissionService.php
=> fix: excel date format

src/Controller/ContentManagement/AssetController.php, src/Form/View/GalleryViewType.php, src/Form/View/KeywordsViewType.php, src/Resources/config/controllers.xml, src/Resources/translations/EMSCoreBundle.en.yml
There is still some es7 issues
=> fix: hotfixes

src/Controller/ContentManagement/FileController.php, src/Controller/UploadedFileController.php, src/Resources/config/routing/all.xml, src/Resources/views/elements/side-menu.html.twig
Give access to uploaded files overview to Publishers
=> refactor: upload files for publisher

src/Entity/UploadedAsset.php
- fix: default value fo UploadedAsset hidden field #656
=> Release 1.15.5

composer.json, src/Repository/ManagedAliasRepository.php
|Bug fix?       ||
Replace_With_One_Paragraph_Description
=> chore: phpstan + deprecation

composer.json, doc/twig/datatable.md, src/Controller/ContentManagement/DatatableController.php, src/DependencyInjection/EMSCoreExtension.php, src/Form/Data/ElasticaRow.php, src/Form/Data/ElasticaTable.php, src/Form/Data/EntityTable.php, src/Form/Data/TableAbstract.php, src/Form/Data/TableColumn.php, src/Form/Data/TemplateTableColumn.php, src/Helper/DataTableRequest.php, src/Repository/ManagedAliasRepository.php, src/Resources/config/controllers.xml, src/Resources/config/routing/all.xml, src/Resources/config/routing/datatable.xml, src/Resources/config/runtime.xml, src/Resources/config/services.xml, src/Resources/views/datatable/ajax.html.twig, src/Resources/views/datatable/dom.html.twig, src/Resources/views/datatable/excel-cell.html.twig, src/Resources/views/form/forms.html.twig, src/Service/DatatableService.php, src/Service/SearchService.php, src/Twig/AppExtension.php, src/Twig/DatatableRuntime.php
* feat: emsco_datatable twig function (#655) + doc
* feat: emsco_datatable_excel_path + doc
=> build: 1.15.7

doc/twig/datatable.md, src/Form/Data/ElasticaTable.php
|Deprecations?  |y|	
|Fixed tickets  |y|
=> feat: better dt sort

assets/js/EmsListeners.js, assets/js/helpers.js, src/Controller/ElasticsearchController.php, src/Controller/Search/QuerySearchController.php, src/Core/Document/DataLinks.php, src/Entity/QuerySearch.php, src/Form/DataTransformer/QuerySearchOptionsTransformer.php, src/Form/Field/ObjectPickerType.php, src/Form/Field/QuerySearchPickerType.php, src/Form/Form/QuerySearchType.php, src/Repository/QuerySearchRepository.php, src/Resources/DoctrineMigrations/pdo_pgsql/Version20210506131424.php, src/Resources/config/controllers.xml, src/Resources/config/routing/all.xml, src/Resources/config/routing/search.xml, src/Resources/config/services.xml, src/Resources/views/query-search/edit.html.twig, src/Service/QuerySearchService.php
|Bug fix?       ||
|Fixed tickets  ||
=> feat: querySearch js

.github/workflows/code_quality.yml
=> fix: stay php7

src/Service/Channel/ChannelRegistrar.php
Channel could not be converted to string
=> fix: Channel could not be converted to string

src/Resources/DoctrineMigrations/pdo_mysql/Version20210522204436.php, src/Resources/DoctrineMigrations/pdo_sqlite/Version20210522204603.php
Apply last schema updates to mysql and sqlite
=> chore: doctrine migrate

src/Entity/Revision.php
debug in DataService array_merge with getDataRaw (when no data)
=> fix: raw data revision

src/Command/MigrateCommand.php
=> fix: invalid options for archive command

composer.json
=> fix: remove require domPdf (handled by common)

src/Controller/ContentManagement/AssetController.php, src/Resources/config/controllers.xml, src/Resources/config/routing/asset.xml, src/Service/Channel/ChannelRegistrar.php
Better solution to proxy channel assets
=> refactor: move proxy controller in the core

doc/twig/datatable.md, src/Controller/ContentManagement/DatatableController.php, src/Form/Data/ElasticaTable.php, src/Resources/config/routing/datatable.xml, src/Service/DatatableService.php, src/Twig/AppExtension.php, src/Twig/DatatableRuntime.php
new emsco_datatable_csv_path filter and its related route/export
=> feat: twig function emsco_datatable_csv_path

src/Controller/ContentManagement/AssetController.php, src/Resources/config/controllers.xml
Redirect assets request from referrer (not proxying the request anymore)
=> refactor: redirect to assets

src/Controller/ChannelController.php, src/Entity/Channel.php, src/Form/Data/TableColumn.php, src/Resources/views/form/forms.html.twig
|Deprecations?  |y|	
|Fixed tickets  |y|	
Add a link to the channel entry
=> feat: channel path link

src/Controller/Search/QuerySearchController.php, src/Core/Document/DataLinks.php, src/Service/QuerySearchService.php
Take into account the query string and tghe paging and the content type icon and the content type label
=> feat: dyn query search

src/Resources/translations/EMSCoreBundle.en.yml
Suggestion for label in channel creation form
=> chore: improvement on channel label

doc/contentTypes/transformers.md, src/Core/ContentType/Transformer/AbstractTransformer.php, src/Core/ContentType/Transformer/ContentTransformer.php, src/Core/ContentType/Transformer/HtmlAttributeTransformer.php, src/Core/ContentType/Transformer/HtmlEmptyTransformer.php, src/Form/DataField/Options/MigrationOptionsTransformerType.php, src/Resources/config/services.xml, tests/Unit/Core/ContentType/Transformer/AbstractTransformerTest.php, tests/Unit/Core/ContentType/Transformer/HtmlAttributeTransformerTest.php, tests/Unit/Core/ContentType/Transformer/HtmlEmptyTransformerTest.php
Clean empty html content (see docs)
=> feat: html empty transformer

src/Resources/views/form/fields/json_menu_nested_editor.html.twig
Show add button if you have the rights for the child.
=> fix: json menu nested add button role

src/Form/Form/RevisionType.php
=> fix: silent placeholder not showing

src/Form/Form/RevisionType.php, src/Resources/DoctrineMigrations/pdo_pgsql/Version20201215133710.php
=> fix: form submisison doctrine migration

src/Core/ContentType/Transformer/HtmlEmptyTransformer.php
=> fix: 1.15.14

doc/twig/datatable.md, doc/twig/revision.md, src/Common/DocumentInfo.php, src/Controller/ContentManagement/DatatableController.php, src/Controller/ContentManagement/EnvironmentController.php, src/Core/ContentType/Transformer/HtmlEmptyTransformer.php, src/Entity/Revision.php, src/Form/Data/ElasticaTable.php, src/Repository/RevisionRepository.php, src/Resources/config/routing/datatable.xml, src/Resources/config/services.yml, src/Resources/views/datatable/excel-cell.html.twig, src/Resources/views/datatable/row.json.twig, src/Resources/views/form/forms.html.twig, src/Service/Revision/RevisionService.php, src/Twig/AppExtension.php, src/Twig/RevisionRuntime.php
=> build: 1.15.15

src/Entity/Analyzer.php
=> build: 1.15.16

src/Controller/Form/SubmissionController.php, src/Entity/FormSubmission.php, src/Resources/DoctrineMigrations/pdo_mysql/Version20210708145832.php, src/Resources/DoctrineMigrations/pdo_pgsql/Version20210708142915.php, src/Resources/DoctrineMigrations/pdo_sqlite/Version20210708145818.php, src/Resources/translations/EMSCoreBundle.en.yml, src/Service/Form/Submission/FormSubmissionRequest.php
- expire_date can be null in datamodel
- deadline_date is depreacetd
=> fix: form submission

src/Controller/Form/SubmissionController.php, src/Entity/FormSubmission.php, src/Resources/DoctrineMigrations/pdo_mysql/Version20210708145832.php, src/Resources/DoctrineMigrations/pdo_pgsql/Version20210708142915.php, src/Resources/DoctrineMigrations/pdo_sqlite/Version20210708145818.php, src/Resources/translations/EMSCoreBundle.en.yml, src/Resources/views/datatable/ajax.html.twig, src/Service/Form/Submission/FormSubmissionRequest.php
Co-authored-by: David mattei <david.mattei@sappico.be>
* #718 
* #720
* #721
=> build: 1.15.17

src/Command/ContentType/TransformCommand.php
=> fix: transnform cmd execute result

src/Command/ContentType/TransformCommand.php, src/Core/ContentType/Transformer/BaseHtmlTransformer.php, src/Core/ContentType/Transformer/HtmlAttributeTransformer.php, src/Core/ContentType/Transformer/HtmlRemoveNodeTransformer.php, src/Resources/config/services.xml, src/Service/IndexService.php, src/Service/PublishService.php, tests/Unit/Core/ContentType/Transformer/HtmlRemoveNodeTransformerTest.php
- fix: transnform cmd execute result (#729)
- feat: content transformer remove (#722)
=> build: 1.15.19

doc/tricks.md, src/Controller/ContentManagement/DataController.php, src/Controller/ElasticsearchController.php, src/Entity/Form/Search.php, src/EventListener/RequestListener.php, src/Form/DataField/DataLinkFieldType.php, src/Form/DataField/DateFieldType.php, src/Form/DataField/DateRangeFieldType.php, src/Form/DataField/FileAttachmentFieldType.php, src/Form/DataField/IndexedAssetFieldType.php, src/Form/DataField/UrlAttachmentFieldType.php, src/Form/DataField/WysiwygFieldType.php, src/Resources/config/services.xml, src/Service/SearchService.php
=> build: 1.15.20

src/Controller/ChannelController.php, src/Controller/ContentManagement/ActionController.php, src/Controller/ElasticsearchController.php, src/Controller/QuerySearchController.php, src/Controller/Views/CriteriaController.php, src/Entity/ContentType.php, src/Form/Form/TableType.php, src/Repository/ChannelRepository.php, src/Repository/QuerySearchRepository.php, src/Repository/TemplateRepository.php, src/Resources/views/view/custom/criteria_table.html.twig, src/Service/ActionService.php, src/Service/Channel/ChannelService.php, src/Service/IndexService.php, src/Service/ObjectChoiceCacheService.php, src/Service/QuerySearchService.php
Fixes some bugs with the criteria view
=> build: 1.15.22

.gitattributes
=> chore: git export ignore dev files

src/Command/Revision/TaskCreateCommand.php
=> fix: task create command broken

src/Command/Environment/AlignCommand.php
=> fix: align cmd clear cache

src/Controller/ContentManagement/PublishController.php
=> fix: publish ct broken

doc/commands.md, src/Command/ContentType/TransformCommand.php, src/Command/Environment/AlignCommand.php, src/Command/JobCommand.php, src/Command/JobOutput.php, src/Controller/ContentManagement/DataController.php, src/Controller/ContentManagement/PublishController.php, src/Core/ContentType/Transformer/ContentTransformer.php, src/Core/Revision/Search/RevisionSearcher.php, src/Form/View/ExportViewType.php, src/Repository/JobRepository.php, src/Resources/config/services.xml, src/Resources/config/view_types.xml, src/Resources/views/action/form.html.twig, src/Service/EnvironmentService.php, src/Service/JobService.php
- #765
- #767 
- #768 
- #769 
- https://github.com/ems-project/EMSCoreBundle/commit/ffb6984291834a04b3e7bfaf122445613deb60d4
- https://github.com/ems-project/EMSCommonBundle/pull/292
- https://github.com/ems-project/EMSCommonBundle/pull/297
=> build: 1.16.4

src/Core/Revision/Task/TaskEventSubscriber.php, src/Core/Revision/Task/TaskLog.php, src/Core/Revision/Task/TaskManager.php, src/Entity/Task.php, src/Resources/views/revision/task/ajax.twig
- delete task with no description
- fa-flag-checkered -> fa-check
- better log changed assignee
=> fix: tasks

doc/twig/revision.md, src/Repository/RevisionRepository.php, src/Service/Revision/RevisionService.php, src/Twig/AppExtension.php, src/Twig/RevisionRuntime.php
=> feat: twig function emsco_revisions_draft

src/Controller/ContentManagement/FileController.php, src/Controller/UploadedFileController.php, src/Resources/translations/EMSCoreBundle.en.yml, src/Service/FileService.php
if needed just synch assets on a new storage service after some soft cleaning
|Deprecations?  |y|	
|Fixed tickets  |b|	
Dangerous and useless
=> refactor: remove hard delete functionality for asset

src/Resources/views/data/edit-revision.html.twig
=> fix(views): try to access to un-existed key in edit-revision

README.md, src/Resources/translations/EMSCoreBundle.en.yml, src/Resources/translations/emsco-twigs.en.yml, src/Resources/views/action/action.html.twig, src/Resources/views/action/add.html.twig, src/Resources/views/action/edit.html.twig, src/Resources/views/action/form.html.twig, src/Resources/views/action/index.html.twig, src/Resources/views/elasticsearch/add-alias.html.twig, src/Resources/views/elasticsearch/export-search.html.twig, src/Resources/views/elasticsearch/no-nodes-available.html.twig, src/Resources/views/elasticsearch/save-search.html.twig, src/Resources/views/elasticsearch/search-form-filter.html.twig, src/Resources/views/elasticsearch/search.html.twig, src/Resources/views/elasticsearch/status.html.twig, src/Resources/views/elements/revision-toolbar.html.twig, src/Resources/views/elements/side-menu.html.twig, src/Resources/views/macros/data-field-type.html.twig
Refactor some twig translations
=> refactor: some twig translations

doc/contentTypes/actions.md, src/Form/Field/RenderOptionType.php, src/Resources/views/elements/object-views-button.html.twig
=> feat: new action render option html

src/Core/Revision/DraftInProgress.php, src/Resources/views/elements/get-button.html.twig
Better draft in progress's actions
=> refactor: sugestion to have edit in front and remove useless icon

doc/twig/core.md, src/Resources/config/runtime.xml, src/Twig/AppExtension.php, src/Twig/CoreRuntime.php
=> feat: emsco_log_notice|warning|error

src/Command/MigrateCommand.php, src/Command/Revision/ArchiveCommand.php, src/Commands.php
=> refactor: archive command use constants

src/Contracts/Revision/RevisionServiceInterface.php, src/DependencyInjection/EMSCoreExtension.php, src/Repository/RevisionRepository.php, src/Resources/config/contracts.xml, src/Service/Revision/RevisionService.php, src/Twig/RevisionRuntime.php
=> refactor: revision service contract for search

src/Command/MigrateCommand.php, src/Command/Revision/ArchiveCommand.php, src/Commands.php, src/Contracts/Revision/RevisionServiceInterface.php, src/DependencyInjection/EMSCoreExtension.php, src/Repository/RevisionRepository.php, src/Resources/config/contracts.xml, src/Service/Revision/RevisionService.php, src/Service/SearchService.php, src/Twig/AppExtension.php, src/Twig/RevisionRuntime.php
=> build: 1.16.9

src/Form/Form/RevisionType.php, src/Resources/views/data/edit-revision.html.twig
=> fix: translation publish modal

src/Command/JobOutput.php, src/Service/JobService.php
- Parse job input correctly with StringInput
- Keep verbosity level on normal for output
=> fix: job output input

src/Resources/translations/EMSCoreBundle.en.yml, src/Service/PublishService.php
=> fix: not locked publish versioned revision

src/Resources/views/analyzer/add.html.twig, src/Resources/views/analyzer/index.html.twig, src/Resources/views/channel/add.html.twig, src/Resources/views/channel/edit.html.twig, src/Resources/views/query-search/form.html.twig
=> fix: wrong dom

src/Controller/Dashboard/DashboardController.php
=> fix: delete at end

src/Controller/Api/File/ExtractDataController.php, src/Resources/config/controllers.xml, src/Resources/config/routing/all.xml, src/Resources/config/routing/api/extract-data.xml
New extract data from asset api
=> feat: api extract data from asset

src/Controller/ContentManagement/ReleaseController.php, src/Entity/ReleaseRevision.php, src/Form/Data/Condition/NotEmpty.php, src/Form/Data/TableColumn.php, src/Repository/ReleaseRevisionRepository.php, src/Resources/translations/EMSCoreBundle.en.yml, src/Resources/translations/emsco-twigs.en.yml, src/Resources/views/form/forms.html.twig, src/Resources/views/release/columns/release-revisions.html.twig, src/Service/ReleaseRevisionService.php, src/Service/ReleaseService.php
Rollback and compare in releases
=> feat: release rollback

src/Resources/translations/emsco-forms.en.yml
Just a typo in 1 tranlation key
=> chore: type sidebar menu

src/Controller/Api/Search/SearchController.php, src/Controller/ContentManagement/PublishController.php, src/Resources/config/routing/api/search.xml, src/Service/SearchService.php
Expose more endpoints in the search api
=> feat: advance search api

doc/commands.md
Some documentation about XLIFF commands
=> doc: xliff

src/Service/Internationalization/XliffService.php
if source's environment and target's environments are the same
=> fix: target can't be final

src/Service/ContentTypeService.php
Regression old views are hidden
=> fix: view without role are hidden

src/Resources/views/view/index.html.twig
=> fix: route with name not id

assets/cke-plugins/adv_link/lang/nl.js, src/Entity/Helper/JsonNormalizer.php
=> fix: phpstan

src/Resources/views/dashboard/services/error.html.twig, src/Resources/views/dashboard/services/template.html.twig, src/Resources/views/datatable/dom.html.twig, src/Resources/views/release/add.html.twig, src/Resources/views/release/edit.html.twig, src/Resources/views/release/revisions.html.twig, src/Resources/views/release/view.html.twig
=> fix: tag html typos

assets/cke-plugins/adv_link/dialogs/link.js, assets/cke-plugins/adv_link/plugin.js, src/Controller/ContentManagement/ContentTypeController.php, src/Resources/public/js/cke-plugins/adv_link/dialogs/link.js, src/Resources/public/js/cke-plugins/adv_link/plugin.js
=> fix: remove asset url type for wysiwyg

src/Entity/Form/SearchFilter.php, src/Form/Subform/SearchFilterType.php
=> feat: gt, gte, lt and lte operators

src/Service/Revision/PostProcessingService.php
Fix: post process in multiplex filed type
=> feat: postprocess in multiplex

src/Entity/Form/SearchFilter.php, src/Form/Subform/SearchFilterType.php, src/Service/Revision/PostProcessingService.php
=> build: 1.17.2

src/Form/Field/RolePickerType.php
=> fix: role-picker default empty string

src/Command/Revision/DiscardDraftCommand.php, src/Commands.php, src/Resources/config/command.xml
=> feat: discard draft command

src/Command/Revision/ArchiveCommand.php, src/Command/Revision/DiscardDraftCommand.php, src/Entity/Revision.php
Don't discard locked revision + older than option in the discard-draft command
=> feat: discard older

package-lock.json, package.json, webpack.config.js
Before building we should clean the src/Resources/public folder, otherwise you will have a lot of new files.
=> chore: clean webpack

src/Resources/views/macros/data-field-type.html.twig
Comparing a revision with a multiple selection against a revision without cause an error.
=> fix: compare user select property field

src/Form/DataField/CollectionFieldType.php
By default collection will renumbered
=> feat: new collection will renumbered by default

src/Controller/ContentManagement/DataController.php, src/Resources/translations/EMSCoreBundle.en.yml
=> refactor: compare no more beta

src/Resources/views/form/fields.html.twig
=> feat: browse from server also from regular asset field

src/Form/Field/ObjectChoiceListItem.php
Fix an issue if a non string field is defined as label field (i.e. an integer)
=> fix: an issue where the label field is an integer

src/Core/Revision/Wysiwyg/WysiwygRuntime.php, src/Entity/User.php, src/Entity/UserInterface.php, src/Security/CoreLdapUser.php
Replace_With_One_Paragraph_Description
=> fix: wysiwyg runtime error no profile

src/Core/Revision/Wysiwyg/WysiwygRuntime.php, src/Entity/User.php, src/Entity/UserInterface.php, src/Security/CoreLdapUser.php
=> fix: wysiwyg runtime error

src/Resources/config/services.yml, src/Twig/AppExtension.php
Use a asset runtime route when a name and a type can be determine
=> fix: use an asset runtime route if available

doc/twig/datatable.md, src/Form/Data/ElasticaTable.php
=> feat: default sort in datatable twig functions

doc/tricks.md, src/Form/DataField/MultiplexedTabContainerFieldType.php, src/Resources/views/form/fields.html.twig, src/Resources/views/macros/data-field-type.html.twig
If a multiplex field is inside a tabs field it will be generated a regular tabs inside the tabs field
=> feat: all tabs in one

assets/cke-plugins/adv_link/dialogs/link.js, src/Resources/public/js/cke-plugins/adv_link/dialogs/link.js
The CKE plugin adv_link is not able to load file with Firefox (due to iframe issue)
=> fix: ckeditor file upload firefox

src/Resources/views/macros/data-field-type.html.twig
in some case the tabs identifiers are wrong
=> fix: forget counter

src/Controller/ContentManagement/DataController.php, src/Controller/Revision/EditController.php, src/Resources/translations/EMSCoreBundle.en.yml
=> refactor: simplified auto-saved message

src/Repository/TaskRepository.php
Task must ignore non current revision
=> fix: don't take non-current revision

src/Controller/ContentManagement/DataController.php, src/Controller/Revision/EditController.php, src/Repository/TaskRepository.php, src/Resources/translations/EMSCoreBundle.en.yml, src/Resources/views/macros/data-field-type.html.twig
=> build: 1.17.11

src/Resources/views/data/edit-revision.html.twig, src/Resources/views/elements/revision-toolbar.html.twig, src/Resources/views/revision/json/json_menu_nested.html.twig
=> refactor: Use ellipsis icon in more options dropdown menu

src/Command/ExportDocumentsCommand.php, src/Entity/Template.php, src/Service/TemplateService.php
=> build: 1.17.16

src/Command/ExportDocumentsCommand.php
=> fix: missing extension

src/Resources/config/routing/data.xml
=> fix: the CT's option require the post method

src/Resources/config/routing/user.xml
=> fix: delete not edit

src/Command/ExportDocumentsCommand.php, src/Resources/config/routing/data.xml, src/Resources/config/routing/user.xml
=> build: 1.17.17

src/Resources/translations/EMSCoreBundle.en.yml, src/Resources/views/release/form.html.twig
=> refactor: labels buttons order

src/Controller/Revision/EditController.php, src/Service/Revision/RevisionService.php
Pass the form object on saveVersion, that way the controller know correctly if there were any error. FinalizeDraft will attach these errors.
=> fix: version revision form validation

doc/routes.md, src/Controller/ContentManagement/ReleaseController.php, src/Controller/Revision/EditController.php, src/Entity/ReleaseRevision.php, src/Entity/Revision.php, src/Form/Data/EntityTable.php, src/Repository/ReleaseRepository.php, src/Resources/config/routing/data.xml, src/Resources/translations/EMSCoreBundle.en.yml, src/Resources/views/elements/revision-toolbar.html.twig, src/Resources/views/release/add-to-release.html.twig, src/Resources/views/release/form.html.twig, src/Routes.php, src/Service/ReleaseService.php, src/Service/Revision/RevisionService.php
=> build: 1.17.20

src/Resources/views/elements/revision-toolbar.html.twig
=> fix: twig dump

src/Entity/FieldType.php, src/Form/DataField/Options/RestrictionOptionsType.php
=> fix: chidren field in json nested menu

src/Resources/translations/EMSCoreBundle.en.yml, src/Resources/views/elements/object-views-button.html.twig
=> refactor: corresponding-revision is useless

src/Core/Dashboard/DashboardManager.php, src/Entity/Dashboard.php, src/Resources/DoctrineMigrations/pdo_mysql/Version20220214221213.php, src/Resources/DoctrineMigrations/pdo_pgsql/Version20220214220708.php, src/Resources/DoctrineMigrations/pdo_sqlite/Version20220214221223.php, src/Resources/config/services.xml
=> feat: dashboard admin api

src/Service/ObjectChoiceCacheService.php
=> fix: $type might be missing

src/Resources/views/macros/data-field-type.html.twig
New path parameter that is transmitted recursively
=> fix: issue with tabs in collections

src/Entity/Helper/JsonClass.php, src/Entity/QuerySearch.php, src/Resources/config/services.xml, src/Service/QuerySearchService.php
|Deprecations?  |y|	
|Fixed tickets  |y|	
- Helper to replace link entities by their name in serialization
- QuerySearchService fully supports the EntityServiceInterface
=> feat: query search admin

src/Core/Mapping/FilterManager.php, src/Entity/Filter.php, src/Repository/FilterRepository.php, src/Resources/config/services.xml
=> feat: Filter implements EntityServiceInterface

src/Core/Mapping/AnalyzerManager.php, src/Entity/Analyzer.php, src/Repository/AnalyzerRepository.php, src/Resources/config/services.xml
=> feat: analyzer admin api

src/Entity/Revision.php, src/Resources/views/data/revisions-data.html.twig
=> feat: revision print version tag in title

src/Core/Job/ScheduleManager.php, src/Entity/Schedule.php, src/Repository/ScheduleRepository.php, src/Resources/config/services.xml
=> feat: schedule admin

src/Controller/I18nController.php, src/Entity/I18n.php, src/Repository/I18nRepository.php, src/Resources/config/repositories.xml, src/Resources/config/routing/api/admin.xml, src/Resources/config/services.yml, src/Service/I18nService.php
=> feat: i18n admin

src/Controller/UserController.php, src/Entity/User.php, src/Form/DataField/WysiwygFieldType.php, src/Form/Form/UserType.php, src/Resources/DoctrineMigrations/pdo_mysql/Version20220217153831.php, src/Resources/DoctrineMigrations/pdo_pgsql/Version20220217151025.php, src/Resources/DoctrineMigrations/pdo_sqlite/Version20220101085539.php, src/Resources/DoctrineMigrations/pdo_sqlite/Version20220104230217.php, src/Resources/DoctrineMigrations/pdo_sqlite/Version20220217155553.php, src/Resources/config/form.xml, src/Resources/translations/emsco-forms.en.yml, src/Resources/views/user/add.html.twig, src/Resources/views/user/edit.html.twig
=> feat: user locale fields

src/Core/Dashboard/DashboardManager.php, src/Entity/Dashboard.php
=> fix: dashboard are identified by their name (not uuid)

src/Controller/Api/Admin/EntitiesController.php, src/Resources/config/controllers.xml, src/Resources/translations/ems_logger.en.yml
=> feat: EntitiesController.php's logs

src/Entity/ContentType.php, src/Service/ContentTypeService.php
In order to avoid changes in exported json
=> fix: check if a ct needs to be reordered on update

src/Controller/Api/Admin/MetaController.php, src/Resources/config/controllers.xml, src/Resources/config/routing/all.xml, src/Resources/config/routing/api/meta.xml
=> feat: meta api endpoint

src/Controller/Api/Admin/EntitiesController.php, src/Controller/Api/Admin/MetaController.php, src/Core/Dashboard/DashboardManager.php, src/Entity/ContentType.php, src/Entity/Dashboard.php, src/Resources/config/controllers.xml, src/Resources/config/routing/all.xml, src/Resources/config/routing/api/meta.xml, src/Resources/translations/ems_logger.en.yml, src/Service/ContentTypeService.php
#Features
- #980 
- #982 
#Fixes
- #979 
- #981
=> build: 1.17.25

src/Controller/ContentManagement/EnvironmentController.php, src/Controller/ContentManagement/JobController.php, src/Controller/ContentManagement/ManagedAliasController.php, src/Controller/ElasticsearchController.php, src/Controller/I18nController.php, src/Controller/NotificationController.php, src/DependencyInjection/EMSCoreExtension.php
=> fix: phpstan issue getParameter

src/Controller/ContentManagement/ReleaseController.php
=> refactor: maad request

src/Resources/views/base-light.html.twig, src/Resources/views/base.html.twig
=> fix: remove old subtitle

src/Command/ReindexCommand.php, src/Entity/Revision.php, src/Service/Revision/PostProcessingService.php
=> fix: reindex should reload

doc/twig/i18n.md, src/Command/ReindexCommand.php, src/Controller/ContentManagement/ContentTypeController.php, src/Controller/ContentManagement/PublishController.php, src/Controller/I18nController.php, src/Entity/I18n.php, src/Entity/Revision.php, src/Repository/RevisionRepository.php, src/Resources/config/runtime.xml, src/Resources/views/base-light.html.twig, src/Resources/views/base.html.twig, src/Service/I18nService.php, src/Service/PublishService.php, src/Service/Revision/PostProcessingService.php, src/Twig/AppExtension.php, src/Twig/I18nRuntime.php, tests/Unit/Twig/I18nRuntimeTest.php
- #996 
- #995 
- #994 
- #999 
- #1000 
- #997
=> build: 1.17.27

src/Form/UserProfileType.php, src/Resources/views/Profile/edit_content.html.twig
=> feat: edit user locale and preferred locale

src/Core/UI/Menu.php, src/Service/ContentTypeService.php
=> fix: ensure that a content type menu entry has at least one item

src/Controller/Revision/EditController.php
=> fix: or not and and typo

src/Controller/ContentManagement/AnalyzerController.php, src/Resources/config/controllers.xml, src/Resources/config/routing/all.xml, src/Resources/config/routing/analyzer.xml
=> refactor: analyzer controller

src/Controller/ContentManagement/ContentTypeController.php, src/Repository/ContentTypeRepository.php, src/Resources/config/controllers.xml, src/Resources/config/routing/all.xml, src/Resources/config/routing/content-type.xml
=> refactor: content type's controller

src/Controller/WysiwygController.php, src/Resources/config/controllers.xml, src/Resources/config/routing/all.xml, src/Resources/config/routing/wysiwyg-options.xml
=> refactor: wysiwyg controller

src/Controller/ContentManagement/FilterController.php, src/Resources/config/controllers.xml, src/Resources/config/routing/all.xml, src/Resources/config/routing/filter.xml
=> refactor: filter controller

src/Controller/Api/Form/SubmissionController.php, src/Controller/Api/Form/VerificationController.php, src/Controller/AuthTokenController.php, src/Controller/ContentManagement/CrudController.php, src/Resources/config/controllers.xml, src/Resources/config/routing/all.xml, src/Resources/config/routing/interface.xml
=> refactor: crud controller

src/Controller/ContentManagement/IndexController.php, src/Resources/config/controllers.xml, src/Resources/config/routing/all.xml, src/Resources/config/routing/indexes.xml
=> refactor: IndexController

src/Controller/ContentManagement/ManagedAliasController.php, src/Resources/config/controllers.xml, src/Resources/config/routing/all.xml, src/Resources/config/routing/managed-alias.xml
=> refactor: managed alias controller

src/Controller/SearchController.php, src/Resources/config/controllers.xml, src/Resources/config/routing/all.xml, src/Resources/config/routing/search-options.xml
=> refactor: search controller

src/Controller/ContentManagement/EnvironmentController.php, src/Resources/config/controllers.xml, src/Resources/config/routing/all.xml, src/Resources/config/routing/environment.xml, src/Resources/config/routing/publisher.xml
=> refactor: environment controller

src/Controller/I18nController.php, src/Resources/config/controllers.xml, src/Resources/config/routing/all.xml, src/Resources/config/routing/i18n.xml
=> refactor: I18nController's routes

src/Controller/ContentManagement/ActionController.php, src/Resources/config/routing/action.xml, src/Resources/config/routing/all.xml, src/Resources/config/routing/template-deprecated.xml
=> refactor: ActionController's routes

src/Controller/UploadedFileWysiwygController.php
=> refactor: useless and deprecated function

composer.json
=> refactor: remove sensio/framework-extra-bundle dependency

src/Resources/views/base-light.html.twig, src/Resources/views/base.html.twig, src/Resources/views/contenttype/reorder_item.html.twig, src/Resources/views/elements/pagination.html.twig, src/Resources/views/elements/sortable-th.html.twig, src/Resources/views/entity/form.html.twig, src/Resources/views/environment/index.html.twig, src/Resources/views/form/fields.html.twig, src/Resources/views/macros/data-field-type.html.twig, src/Resources/views/types/ouuid.html.twig, src/Resources/views/types/string.html.twig
=> refactor: twig deprecations

src/Controller/ContentManagement/EnvironmentController.php, src/Controller/ContentManagement/JobController.php, src/Controller/ContentManagement/ManagedAliasController.php, src/Controller/ElasticsearchController.php, src/Controller/I18nController.php, src/Controller/NotificationController.php, src/Resources/config/controllers.xml
=> refactor: getParameter from controller.xml

composer.json
For resolving entities in our controller actions we need the sensio/framework-extra-bundle
=> fix: we need sensio/framework-extra-bundle

composer.json
=> build: 1.18.1

src/Helper/Xliff/Extractor.php, tests/Unit/Core/Resources/Xliff/Extractions/TC-1/expected_UTF-81.2.xlf, tests/Unit/Core/Resources/Xliff/Extractions/TC-1/expected_UTF-82.0.xlf, tests/Unit/Core/Resources/Xliff/Extractions/TC-1/expected_us-ascii1.2.xlf, tests/Unit/Core/Resources/Xliff/Extractions/TC-1/expected_us-ascii2.0.xlf, tests/Unit/Core/Resources/Xliff/Extractions/TC-2/expected_UTF-81.2.xlf, tests/Unit/Core/Resources/Xliff/Extractions/TC-2/expected_UTF-82.0.xlf, tests/Unit/Core/Resources/Xliff/Extractions/TC-2/expected_us-ascii1.2.xlf, tests/Unit/Core/Resources/Xliff/Extractions/TC-2/expected_us-ascii2.0.xlf, tests/Unit/Core/Resources/Xliff/Extractions/TC-3/expected_UTF-81.2.xlf, tests/Unit/Core/Resources/Xliff/Extractions/TC-3/expected_UTF-82.0.xlf, tests/Unit/Core/Resources/Xliff/Extractions/TC-3/expected_us-ascii1.2.xlf, tests/Unit/Core/Resources/Xliff/Extractions/TC-3/expected_us-ascii2.0.xlf, tests/Unit/Core/Resources/Xliff/Extractions/TC-4/expected_UTF-81.2.xlf, tests/Unit/Core/Resources/Xliff/Extractions/TC-4/expected_UTF-82.0.xlf, tests/Unit/Core/Resources/Xliff/Extractions/TC-4/expected_us-ascii1.2.xlf, tests/Unit/Core/Resources/Xliff/Extractions/TC-4/expected_us-ascii2.0.xlf, tests/Unit/Core/Resources/Xliff/Extractions/TC-5/expected_UTF-81.2.xlf, tests/Unit/Core/Resources/Xliff/Extractions/TC-5/expected_UTF-82.0.xlf, tests/Unit/Core/Resources/Xliff/Extractions/TC-5/expected_us-ascii1.2.xlf, tests/Unit/Core/Resources/Xliff/Extractions/TC-5/expected_us-ascii2.0.xlf, tests/Unit/Core/Resources/Xliff/Extractions/TC-6/expected_UTF-81.2.xlf, tests/Unit/Core/Resources/Xliff/Extractions/TC-6/expected_UTF-82.0.xlf, tests/Unit/Core/Resources/Xliff/Extractions/TC-6/expected_us-ascii1.2.xlf, tests/Unit/Core/Resources/Xliff/Extractions/TC-6/expected_us-ascii2.0.xlf, tests/Unit/Core/Resources/Xliff/Extractions/TC-7/expected_UTF-81.2.xlf, tests/Unit/Core/Resources/Xliff/Extractions/TC-7/expected_UTF-82.0.xlf, tests/Unit/Core/Resources/Xliff/Extractions/TC-7/expected_us-ascii1.2.xlf, tests/Unit/Core/Resources/Xliff/Extractions/TC-7/expected_us-ascii2.0.xlf
=> feat: xliff state

src/Controller/ContentManagement/FileController.php, src/Resources/config/controllers.xml
Move dependency injection to construct of FileController
=> fix: file controller regression

doc/twig/jsonMenuNested.md
=> chore: update json menu nested documentation

doc/twig/jsonMenuNested.md, src/Controller/ContentManagement/FileController.php, src/Resources/config/controllers.xml
=> build: 1.18.3

src/Resources/config/services.yml, src/Twig/UserRuntime.php
emsco_users_enabled was not working anymore
=> fix: twig emsco_users_enabled

src/Form/DataField/AssetFieldType.php, src/Resources/config/routing/public.xml, src/Resources/config/services.yml, src/Twig/UserRuntime.php
=> build: 1.18.4

doc/commands.md, doc/elasticms.md, src/Command/Revision/TaskCreateCommand.php, src/Service/DataService.php
Default owner on creation new revision
Default owner field option for task create command
=> fix: default ownership

src/Command/Revision/ArchiveCommand.php, src/Resources/config/command.xml
=> feat: archive command with query

doc/commands.md, doc/elasticms.md, src/Command/Revision/ArchiveCommand.php, src/Command/Revision/TaskCreateCommand.php, src/Resources/config/command.xml, src/Service/DataService.php
=> build: 1.18.6

src/Command/Revision/ArchiveCommand.php
=> fix: archive command go on contentType

src/Resources/views/i18n/new.html.twig, src/Resources/views/view/custom/criteria_view.html.twig
=> fix: wrong asset path

src/DependencyInjection/EMSCoreExtension.php, src/Resources/views/base.html.twig
=> feat: use ems_version from common bundle

src/Form/DataField/DateTimeFieldType.php, src/Resources/config/routing/content-type.xml
=> build: 1.19.3

src/Resources/config/routing/api/admin.xml
=> fix: api start job route broken

src/Service/Internationalization/XliffService.php
Bugfixes: missing translation and better isHtml
=> fix: xliff limit cases

src/DependencyInjection/EMSCoreExtension.php, src/Resources/config/controllers.xml, src/Resources/config/log.xml, src/Resources/config/services.yml
=> refactor(log): define core logger by common factory

src/Service/Internationalization/XliffService.php
=> fix: non-required pretty print

src/Resources/views/base-light.html.twig, src/Resources/views/base.html.twig
Avoid admin's pages to be indexed
=> feat: avoid admin s pages to be indexed

src/Resources/views/base-light.html.twig, src/Resources/views/base.html.twig
=> build: 1.22.1

doc/commands.md, src/Command/Environment/AbstractEnvironmentCommand.php, src/Command/Environment/AlignCommand.php, src/Command/Environment/UnpublishCommand.php, src/Commands.php, src/Core/Revision/Search/RevisionSearcher.php, src/Elasticsearch/Bulker.php, src/Repository/RevisionRepository.php, src/Resources/config/command.xml, src/Service/PublishService.php
=> build: 1.23.0

src/Controller/ChannelController.php, src/Resources/views/base.html.twig, src/Resources/views/channel/menu.html.twig
=> feat: add channel shortcuts to top menu

src/Command/Xliff/UpdateCommand.php, src/Service/DataService.php, src/Service/Internationalization/XliffService.php, src/Service/Revision/RevisionService.php, src/Service/UserService.php
=> fix: xliff update

src/Controller/TwigElementsController.php, src/Resources/translations/EMSCoreBundle.en.yml, src/Resources/translations/emsco-twigs.en.yml, src/Resources/views/channel/menu.html.twig
=> refactor: use fa-eye as channel's icon

src/Controller/Revision/DetailController.php
We can only throw an exception if we first try resolving the passed version ouuid.
=> fix: passing version ouuid instead of revsion ouuid

src/Resources/views/macros/data-field-type.html.twig
=> fix: missing icon

src/Controller/ContentManagement/CrudController.php, src/Core/Dashboard/DashboardManager.php, src/Core/Job/ScheduleManager.php, src/Entity/QuerySearch.php, src/Service/Channel/ChannelService.php, src/Service/DataService.php
* fix: fails in dev mode
* fix: nullable ouuid in route
* chore: common's phpstan fixes
Replace_With_One_Paragraph_Description
=> build: 1.25.1

doc/twig/jsonMenuNested.md, src/Core/Revision/Json/JsonMenuNestedDefinition.php, src/Core/Revision/Json/JsonMenuRenderer.php, src/Resources/views/revision/json/json_menu_nested.html.twig, src/Service/NotificationService.php
=> build: 1.25.2

src/Controller/Revision/JsonMenuNestedController.php
=> build: 1.25.3

src/Resources/DoctrineMigrations/pdo_mysql/Version20220716091159.php
=> fix: wrong mysql alter table script

src/Resources/views/data/trash.html.twig, src/Twig/AppExtension.php
the deleted_by revision's field migth by set to null
=> fix: not defined delete by

src/Helper/AssetExtractor/ExtractedData.php, src/Resources/config/runtime.xml, src/Service/AssetExtractorService.php, src/Twig/AppExtension.php, src/Twig/DataExtractorRuntime.php
Add a filter tring to detected the locale of a text
=> feat: emsco_guess_locale filter

doc/twig/extractor.md, src/Helper/AssetExtractor/ExtractedData.php, src/Resources/config/runtime.xml, src/Service/AssetExtractorService.php, src/Twig/AppExtension.php, src/Twig/DataExtractorRuntime.php
Add 2 new filters emsco_guess_locale and emsco_asset_meta
=> feat: metas

doc/twig/extractor.md, src/Helper/AssetExtractor/ExtractedData.php, src/Resources/DoctrineMigrations/pdo_mysql/Version20220716091159.php, src/Resources/config/runtime.xml, src/Resources/views/data/trash.html.twig, src/Service/AssetExtractorService.php, src/Twig/AppExtension.php, src/Twig/DataExtractorRuntime.php
- #1180 
- #1183
- #1189
- #1191
=> build: 1.26.0

src/Common/DocumentInfo.php, src/Form/Form/RevisionType.php
=> fix: doc info align
