Controller/AppController.php, Controller/ContentManagement/EnvironmentController.php, Controller/ContentManagement/ManagedAliasController.php, Entity/ManagedAlias.php, Form/Field/AlignIndexesType.php, Form/Form/ManagedAliasType.php, Repository/EnvironmentRepository.php, Repository/ManagedAliasRepository.php, Resources/config/services.yml, Resources/views/elements/post-button.html.twig, Resources/views/environment/index.html.twig, Resources/views/environment/managed_alias.html.twig, Service/AliasService.php, Validator/Constraints/AliasName.php, Validator/Constraints/AliasNameValidator.php
Environment local and external should only use **1** index, but we want to manage aliases with multiple indexes (indices).
On the environment page we can now view/create/edit and delete managed aliases. Managed aliases are stored in 'managed_alias' table. It's also possible to align managed aliases on their edit page.
Added indexes counter to the unreferenced aliases overview. Disabled the attach function for unreferenced aliases with multiple indexes. And also added the delete function for unreferenced aliases.
=> Feature: managed aliases

Form/Field/ObjectChoiceListItem.php, Form/Field/ObjectPickerType.php
Set the correct title attribute on the select options.
Now select2 will use the html value as title on load.
=> Fix title attribute for object pickers

Service/DataService.php
The dataservice should not check the published datetime field (_published_datetime).
When publishing this is also added after the signing.
=> bugfix: computed sha1 mismatch

composer.json
We should at least require commonBundle 1.6.3
=> fix: update composer requirement for commonBundle

Repository/EnvironmentRepository.php
example env extra info:
{"nl": "https://example-nl.test","fr": "https://example-fr.test"}
example template:
{{ environment.extra|json_decode.nl }}
=> fix: env extra field available in CT template

Command/MigrateCommand.php, Elasticsearch/Bulker.php, Elasticsearch/Index/Mappings.php, Elasticsearch/Index/Settings.php, Elasticsearch/Indexer.php, Resources/config/services.yml, Service/DataService.php
The common bundle should not contain the elasticsearch bulker class.
Because the clientHelperBundle will never bulk documents to
elasticsearch.
improve: add helper objects for import
- Mapping object
- Settings object
- Indexer for creating an index correct
=> Import helpers bulker, indexer, mappings

Twig/AppExtension.php
I think we were already using the dump() function, as this is an implementation of a filter |dump.
Presence of the dump function tested with php bin/console debug:twig
=> phpstan deprecated old dump function in twig

Controller/ContentManagement/FileController.php
When not fully authenticated we should use the emsco_asset_public route.
=> bugfix: redirect ems_asset vs emsco_asset_public

Controller/ContentManagement/CrudController.php, Entity/DataField.php, Form/DataField/DataFieldType.php, Form/FieldType/FieldTypeType.php, Service/DataService.php, phpstan.neon.dist
getNewestRevision never returns null nor empty object
The isset was always true, and the isFound is never really used.
(Always true if getNewestRevision passes, always false if error is thrown)
+ line 86 would fail if this code was valid:
$revision->getRawData(),
=> stan lvl 1: getNewestRevision always returns Revision or throws error

Form/Field/ObjectChoiceList.php, Service/ObjectChoiceCacheService.php
When we load all choices, we don't remember the sort of the already
added choices.
=> bugfix: choice loader sort already added choices

Form/DataField/DataLinkFieldType.php
When changing the order and removing an item from a multiple datalink
field type.
=> hotfix: dataLinkFieldType throws error

Service/PublishService.php
The templates in the skeleton did not refresh after silent publish in
the backend ems. Problem the silent publish action is writing a wrong log
operation (typpo).
=> bugfix: silent publish not working correctly

Controller/ContentManagement/ContentTypeController.php, Entity/ContentType.php, Entity/Helper/JsonClass.php, Entity/SingleTypeIndex.php, Entity/Template.php, Entity/View.php
Export and import of content types is working including views/templates/singletypeindex
BUT all links to "environments" are broken; 
Environments are project specific and to be set manually. Maybe an interface should be added to map imported environments with existing ones? 
And an option that says "use existing environments".
=> improvement: export views/templates/singletypeindex

Controller/ElasticsearchController.php, Resources/views/macros/data-field-type.html.twig, Twig/AppExtension.php
"import _self as" no longer works from inside another macro.
Neither does calling macro's dynamically.
However we use import _self as at the base level in EMSCommonBundle, which is still functioning. So CommonBundle is backward compatible with twig 2.10! (important for our skeleton projects in production). But also operates fine on twig 2.11 (required for EMSCoreBundle form this commit on)
Requires:
https://github.com/ems-project/EMSCommonBundle/pull/47
=> refactor: import _self as macro for twig 2.11

Controller/ContentManagement/DataController.php, Form/DataField/CollectionFieldType.php, Resources/translations/EMSCoreBundle.en.yml, Service/DataService.php, composer.json
With the commit e8776c9c649243b5733691258bfaaf92f60d9f67 the propagateDataToComputedField was removed from the ajaxUpdateAction and  editRevisionAction as those calls was sending emails or incrementing counters. But this commit has disabled the live/ajax error messages.
=> Reactivate the propagateDataToComputedField in the ajaxUpdateAction and  editRevisionAction

Controller/ContentManagement/DataController.php, Resources/views/data/revisions-data.html.twig
With elasticsearch the _all doesn't exits any more. Nevertheless we still would like to use a copy to field to search referrers. So base on the referrers fields we must do a should query with a term query and a match query
=> Support both term and match searches in the referrers search

Resources/views/macros/data-field-type.html.twig
Avoid null pointer exception when a json menu field is not defined
=> bug[twig]: default value on non mandatory json menu field

Controller/ContentManagement/DataController.php
Debug exception to generate a corresponding URL => Parameter "ouuid" for route
"data.revision_in_environment" must match "[^/]++".
|Bug fix?       | Y |
|New feature?   | N |	
|BC breaks?     | N |	
|Deprecations?  | N |	
|Fixed tickets  | N |	
ouuid is used to generate url => "/" is not allowed
=> bug(addAction): the "/" is not allowed for ouuid

Security/CoreLdapUserProvider.php
Regression with older LDAP config, we should not need to force configuration of the new service, even if we are loading it (because the base code is used on multiple websites)
=> hot(ldap):non configured provider when sharing elasticms docker images

Controller/ContentManagement/FileController.php
If the FileService is not initiated the storages services are not registered in a core bundle context
Replace_With_One_Paragraph_Description
=> fix: missing image previews in wysiwyg fields 

Command/RebuildCommand.php
|Bug fix?       |yes|
|New feature?   |no|	
|BC breaks?     |no|	
|Deprecations?  |no|	
|Fixed tickets  |no|	
Rebuilding preview resulted in:
The alias template is now pointing to : ems_preview_20201030_101539
The environment variable was overriden in the for loop.
Causing the environment tobe the default env of the last contentType.
=> fix: ems rebuild switch not working

src/Controller/TwigElementsController.php
IMPORTANT:  Running the following code was causing a big memory usage on
a big cluster.
$client->getCluster()->getHealth()->getStatus();
=> fix: memory issue get cluster health

.php_cs.dist, .travis.yml, composer.json, phpstan.neon.dist
- Locally node_modules was also scanned.
- Phpcs only scan src dir
- Change composer phpstan remove . (use config)
- Change travis config remove .
=> chore(phpstan): fix config paths

src/Form/DataField/JsonMenuNestedEditorFieldType.php
=> fix: the string mapping is deprecated since es5 and replaced by text

src/Entity/Analyzer.php, src/Service/EnvironmentService.php
https://stackoverflow.com/questions/58202006/elasticsearch-7-the-standard-token-filter-has-been-removed
The standard token filter has been removed because it does not change
anything in the stream.
=> fix: es7 remove filter standard

src/Service/AliasService.php
The following error get throwen when doing an ems:env:rebuild on an
empty elasticSearch cluster.
This result set does not contain an aggregation named
counter_aggregation.
=> fix: empty cluster error aggregation

src/Form/DataField/DateRangeFieldType.php, src/Service/ChannelService.php, src/Service/Mapping.php
On a es7 cluster we do not have the _all anymore, so we add it on rebuild.
Fields we want to search on we have to define copy_to -> _all.
=> fix: add _all field on rebuild

src/DependencyInjection/EMSCoreExtension.php, src/Resources/views/channel/index.html.twig, src/Resources/views/form/forms.html.twig
the forms.html.twig is not a theme template. It is a specific twig for forms. It has to be loaded only when it's necessary, but it use the core theme as ancestor
=> fix: remove the forms.html.twig as global form theme

src/Controller/ElasticsearchController.php, src/DependencyInjection/EMSCoreExtension.php, src/Resources/views/channel/index.html.twig, src/Resources/views/elasticsearch/search.json.twig, src/Resources/views/form/forms.html.twig
* fix: dataLink type search broken
Pass Common response to twig template
Clean twig template
* fix: jsonMenuNested modals not working
The channel features introduce a new formTemplate.
JsonMenuNested modals are defined in the form_end, but this was not called anymore!
Because @EMSCore/form/forms.html.twig is more important it should come at the end of the array!
Symfony documentation:
You can pass multiple themes to this option because sometimes form themes only redefine a few elements. This way, if some theme doesn’t override some element, Symfony looks up in the other themes.
The order of the themes in the twig.form_themes option is important. Each theme overrides all the previous themes, so you must put the most important themes at the end of the list.
* fix: remark and phpcs …
=> Release 1.14.32

src/Elasticsearch/Bulker.php
Elastica actions do not support field named 'doc' in source array.
Json stringify the source on the elastica action
=> fix: elastica action field doc

src/Entity/Analyzer.php
Filter fix for es7 was not working for analyzer without filters.
And also failing when putting empty array as filter option
=> HOTFIX: rebuild failing

src/Command/LockCommand.php, src/Command/RecomputeCommand.php, src/Repository/RevisionRepository.php, src/Service/DataService.php
The id is in fact the revision ouuid, renamed id to ouuid.
It is not a int but a string value.
BC option --id becomes --ouuid for ems:contenttype:recompute page --ouuid=cb874acb1d18db6c31cd8c1831bb4991fef15e3c
=> fix: recompute with option id not working

src/Service/NotificationService.php
On treating bulk notifications doctrine was clearing the parent field type 'source' by removing the contentType.
Not the best fix, but clearing the em after 1 treatment fixes the problem for now.
=> fix: treat notifications update fieldType

src/Resources/views/data/view-data.html.twig, src/Resources/views/view/custom/gallery_view.html.twig, src/Resources/views/view/custom/hierarchical_view.html.twig
_type no longer exists in ES7, but was still used in our templates
=> fix: _type to _source._contenttype in templates

composer.json
We are not using this namespace in the core code.
It is a very old requirement introduced on 12/27/2016
CommonBundle now has a requirement on  "phpoffice/phpspreadsheet": "^1.16" which needs "maennchen/zipstream-php": "^2.1".
=> fix: remove maennchen\ZipStream

src/Form/DataField/ChoiceFieldType.php, src/Form/DataField/JsonMenuLinkFieldType.php, src/Form/DataField/JsonMenuNestedLinkFieldType.php, src/Form/DataField/SelectFieldType.php, src/Service/DataService.php
In symfony forms 4.4.20 multiple choices only allow arrays
https://github.com/symfony/form/commit/c03e236d623624d1ee1e71cd4e3a70023f5d18ee
=> fix: choices empty data

src/Resources/views/elasticsearch/search.html.twig
Neither the property "0" nor one of the methods "0()",
"get0()"/"is0()"/"has0()" or "__call()" exist and have public access in
class "Generator".
=> fix: global search twig error

src/Entity/UploadedAsset.php
Default value for UploadedAsset hidden field
=> fix: default value fo UploadedAsset hidden field

src/Service/SearchService.php
a . in a field name also be used to artificially prefix a field, not always a subfield. In case of external defined mapping.
=> fix: non nested sub field

doc/twig/datatable.md, src/Form/Data/ElasticaTable.php, src/Form/Data/TableAbstract.php, src/Form/Data/TableColumn.php, src/Form/Data/TemplateTableColumn.php
Allow to customize the tag and the class attribute of a datatable cell
=> feat: datatable advance options

package-lock.json
Reverts ems-project/EMSCoreBundle#670
=> Revert "chore(deps): bump ssri from 6.0.1 to 6.0.2"

src/Resources/config/routing/asset.xml, src/Service/Channel/ChannelRegistrar.php
if:
- the request starts by /bundles/
- the request referer is in a channel context
The channel's name is not always equal to the channel's alias
=> feat: try to add a channel's alias in request headers

src/Controller/ContentManagement/AssetController.php
- bug when the elasticms doen't have bundle
- font have css referer, so assets that match an alias are saved in saved in session for further referer matching
=> fix: asset proxy for already proxied asset referer

src/Controller/ContentManagement/AssetController.php
- proxy fonts and other asset referenced by  an CSS within a channel context  (#697 )
=> fix: asset proxy for already proxied asset referer (#697)

src/Resources/views/data/revisions-data.html.twig
When no delete role is defined, allow delete revisions.
=> fix: delete button no role defined

src/Twig/AppExtension.php
Only when not viewing the current revision. The datalinks were relative which created the following link: /data/revisions/revisions/page:142c8296e1b8e5e1a82347c26f7dc224af5d10d1
=> fix: datalink not working nested modal

src/Core/Revision/Revisions.php
|Bug fix?       |y
If you bulk more then 250 the archive was not working.
Because entity manager clear was called before
=> fix: archive still not working correct

src/Command/DocumentCommand.php, src/Form/DataField/WysiwygFieldType.php
Fix:
- #734 
- fix: avoid runtime exception on null/missing $data
- chore: phpstan fixes : ensure option type
BC:
Some ems:contenttype:import options have renamed
- `bulkSize` to `bulk-size`
- `businessKey` to `business-key`
=> fix: hot runtime exception (#734)

composer.json
symfony/webpack-encore-pack
This package is abandoned and no longer maintained. The author suggests using the symfony/webpack-encore-bundle package instead.
=> build: fix composer abandoned webpack-encore-pack

src/Entity/DataField.php, src/Resources/views/macros/data-field-type.html.twig
- remove initChild function only used in DataField.php
- twig is using the offsetGet with offset 'children', just return the children.
=> fix: deprecate exception initChild

doc/commands.md, src/Command/ContentType/TransformCommand.php, src/Command/Environment/AlignCommand.php, src/Core/ContentType/Transformer/ContentTransformer.php, src/Core/Revision/Search/RevisionSearcher.php, src/Resources/config/services.xml
- revision searcher no query logging
- align command use transaction with locking (we are signing the rawData)
- align command USER option
- content transform command USER option
- add doc align command
=> fix: commands

src/Command/Environment/AlignCommand.php, src/Command/JobCommand.php, src/Command/JobOutput.php, src/Repository/JobRepository.php, src/Service/EnvironmentService.php, src/Service/JobService.php
- fix: align command update snapshot
> Because the align command uses a transaction -> doctrine clear. We need to do a new findByName before updating the snapshot environment.
- fix: job with sub commands 
> The job output and finish should fetch the job entity again. Because the command or multiple sub commands can clear doctrine for performance reasons.
=> fix: job commands

src/Controller/ContentManagement/DataController.php
Cannot autowire argument $pdfPrinter of "EMS\CoreBundle\Controller\ContentManagement\DataController::customViewAction()": it references class "EMS\CommonBundle\Service\Pdf\DomPdfPrinter" but no such service exists. Try changing the type-hint to "EMS\CommonBundle\Service\Pdf\PdfPrinterInterface" instead.
=> fix: use PdfPrinterInterface

assets/css/_bootstrap-variables.scss
=> fix(css): wrong bootstrap fonts path

src/Repository/RevisionRepository.php, src/Service/SearchService.php, src/Twig/AppExtension.php
Archived documents have no publication (es document) in the default environment. Resolve the label from the last know revision in the database.
- https://github.com/ems-project/EMSCommonBundle/pull/312
=> fix: resolve data_link|label for archive docs

src/Resources/translations/EMSCoreBundle.en.yml, src/Service/ContentTypeService.php
Displays a message instead of a 500 error page on updating mapping
=> fix: exception on mapping error

src/Form/Field/RolePickerType.php
In [29a5e5d140005d00331d1fe1c47e4c3fa410ced2](https://github.com/ems-project/EMSCoreBundle/pull/836/commits/45ca943a6247587abff454342d10f241361ad8a9)  makes the role pickers required
=> fix: role picker type not required by default

src/Resources/config/routing/task.xml
If you use the task feature, it gives a 404 dashboard not found. 
Because it's hitting the emsco_dashboard route /dashboard/{name} and it should go to the task dashboard.
=> fix: task dashboard route prefix

src/Core/Revision/Json/JsonMenuNestedDefinition.php
Previously editable JSON nested field are now readonly
=> fix: by default edit is granted if no minimal role is defined

src/Service/Revision/PostProcessingService.php
=> fix: if we loop on the multiplex field we also need to pass the grandchild

src/Resources/views/wysiwyg_styles_set/iframe.html.twig
Add body class so that we can target the preview rendering
Example:
```css
.pageBody .content,
body.wysiwyg-preview, 
body.cke_editable {
&>* {
margin-bottom: $px15;
margin-left: 0!important;
}
```
=> fix: add body class wysiwyg preview

src/Command/ExportDocumentsCommand.php, src/Entity/Template.php, src/Service/TemplateService.php
Since the document export is usin a command to generate the exports the filename template is ignored. This is the related fix.
=> fix: export's filenames

src/Resources/views/form/forms.html.twig
See src/Form/Form/TableType.php line 73:
if ($data->isSortable() && $data->count() > 1) { ... }
If the datatable only contains 1 record we get an error.
Error:
Neither the property "reordered" nor one of the methods "reordered()", "getreordered()"/"isreordered()"/"hasreordered()" or "__call()" exist and have public access in class "Symfony\Component\Form\FormView".
=> fix: reordered not defined

src/Controller/Revision/EditController.php, src/Form/Form/RevisionType.php
If we edit a not aligned revision, we need to publish the revision on save in the published environments.
=> fix: save and publish not current revision

src/Controller/DashboardController.php, src/Controller/Revision/TaskController.php, src/Core/Dashboard/Services/RevisionTask.php, src/Core/Revision/Task/TaskManager.php, src/Resources/config/dashboards.xml, src/Resources/config/routing/task.xml, src/Resources/translations/emsco-twigs.en.yml, src/Resources/views/revision/task/dashboard.html.twig
Move revision task overview route to a dashboard. This way it can be available on in the sidebar or even default landing page.
=> feat: revision task dashboard

src/Core/DataTable/TableRenderer.php, src/Core/Revision/Task/TaskTableService.php, src/Resources/views/form/forms.html.twig
The revision task dashboard export was containing '<div>value</div>' and version was exported instead of versionTag
=> fix: export revision task from dashboard

src/Controller/ContentManagement/ContentTypeController.php
Otherwise the first ct will have it at 0, and on reimport it will be pushed to the end of the list
=> fix: reorder ct from 1

src/Controller/ContentManagement/PublishController.php, src/Repository/RevisionRepository.php, src/Service/PublishService.php
When we publish a revision that is sharing a version_uuid with other revisions, we need to align/publish also the other revisions.
Otherwise you can have multiple currents revisions in a environment.
=> fix: publish and align versioned revision

src/Entity/Revision.php
When the revision is versioned the label format should be %versionTag% - %label% (%fromDate% - %toDate%)
But also the getLabel should first check the rawData for the label, and fallback to the labelField in the entity. This way when the label changes we receive a correct flash.
=> fix: revision label calculation and versioned

src/Form/DataField/SelectUserPropertyFieldType.php
Fix the selectUserProperty FieldType is now always selecting the first value, we should just not make it required for symfony. The mandatory check on the mapping will add the required assertion.
=> fix: default value selectUserPropertyFieldType

src/Command/ReindexCommand.php
The reload data should only be trigger when we pass the option --reload-data, otherwise the rebuild environment will not work if you start without any indexes. The rebuild is also calling the reindex command.
=> fix: reindex cmd reload-data option

src/Resources/views/revision/json/json_menu_nested.html.twig
They level was not increasing for each item that's why on some items we did not see the ADD button because:
```twig
{%- if 'add' in node.actions and node.addNodes|length > 0 and (def.maxDepth == 0 or level < def.maxDepth) -%}
```
=> fix: json menu nested level

src/Entity/Revision.php, src/Service/DataService.php
Setting meta fields on a revision should first look at the rawData for setting the version tag (Major/Minor,...). Because when we migrate only the rawData is set on the revision. Otherwise all revision will become the default versionTag.
On replaceData we should also call setMetaFields for updating incorrect versionTags from the api.
Plus EMS\CommonBundle\Common\Standard\DateTime was unused on Revision entity
=> fix: version tag from rawData

src/Resources/config/controllers.xml
In the past it was loaded because of the prototype, which was not okay:
https://github.com/ems-project/EMSCoreBundle/commit/2e0afddf37d13df8b9f307854a5b8f5af84dd35b#diff-7619d7a96fa2111a0a538186bc1a6a02bf99c582201cfabdd3b39b0af2227a57
Error:
The controller for URI "/publisher/uploaded-file/" is not callable: Controller "EMS\CoreBundle\Controller\UploadedFileController" has required constructor arguments and does not exist in the container. Did you forget to define the controller as a service?
=> fix: UploadedFileController not defined in controllers.xml

src/Resources/config/controllers.xml
Because the controllers still use the container. Example getDoctrine() (60 search hits).
Commit that removed the autowire: https://github.com/ems-project/EMSCoreBundle/commit/2e0afddf37d13df8b9f307854a5b8f5af84dd35b#diff-7619d7a96fa2111a0a538186bc1a6a02bf99c582201cfabdd3b39b0af2227a57
Info:
https://symfony.com/doc/current/service_container.html#the-autowire-option
https://symfony.com/doc/current/controller/service.html#alternatives-to-base-controller-methods
Currently the old way of defining a search id on a datalink field is broken:
```
Error:
Call to a member function has() on null
at …
```
=> fix: autowire controllers (for now)

src/Controller/ContentManagement/FileController.php, src/Resources/config/routing/api/file.xml, src/Resources/config/routing/data/file.xml
The file upload in web elasticms was using the api chunk, because the on init upload the route parameter $apiRoute was a string "false".
=> fix: api route file upload

src/Resources/config/routing/public.xml
After refactor the /file got removed. The common httpStorage uses this:
https://github.com/ems-project/EMSCommonBundle/blob/a80ace52316a539f387d6c8b89445d6c9c6efacf/src/Storage/Factory/HttpFactory.php#L67
=> fix: prefix file on public download route

src/Form/DataField/AssetFieldType.php
Exception is thrown when the file is not mandatory
=> fix: handle case where AssetFieldType is not mandatory

src/Form/DataField/DateTimeFieldType.php
a datetime string (not throwing an error)
=> fix: only a DataFieldType's message if it's not possible to convert

src/Resources/config/routing/content-type.xml
We can not update a content type from the web interface: 
Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: "No route found for "GET /content-type/json-update/26": Method Not Allowed (Allow: POST)"
=> fix: method get for json-update via ems interface

src/Controller/ElasticsearchController.php, src/Controller/Search/QuerySearchController.php, src/Core/Document/DataLinks.php
When no search or query search and no custom view we should still search offcourse
=> fix: data links default behavior

src/Controller/UploadedFileWysiwygController.php
This is a rollback on #1047, it was not useless because now we get this php error:
> Uncaught Error: Call to protected method Symfony\Bundle\FrameworkBundle\Controller\AbstractController::generateUrl() from context 'EMS\CoreBundle\Form\Data\TableColumn'
> Uncaught PHP Exception Error: "Call to protected method Symfony\Bundle\FrameworkBundle\Controller\AbstractController::generateUrl() from context 'EMS\CoreBundle\Form\Data\TableColumn'" at C:\dev\symfony\smals-elasticms\vendor\elasticms\core-bundle\src\Controller\UploadedFileWysiwygController.php line 86
We forward the controller with use into a callback function, this will throw an php …
=> fix: pick from server broken

src/Controller/AuthTokenController.php, src/Resources/config/controllers.xml, src/Resources/config/services.xml, src/Security/Credentials.php, src/Service/Channel/ChannelRegistrar.php
We should use the parameter "ems_core.security.firewall.core" instead of "main"
The channel registrar should also use this parameter
=> fix: api auth broken & channels

doc/commands.md, src/Command/Environment/AbstractEnvironmentCommand.php, src/Command/Environment/AlignCommand.php, src/Command/Environment/UnpublishCommand.php, src/Commands.php, src/Core/Revision/Search/RevisionSearcher.php, src/Elasticsearch/Bulker.php, src/Repository/RevisionRepository.php, src/Resources/config/command.xml, src/Service/PublishService.php
> Feature request: make a unpublish command which can work with a search query and environment name.
Because the align command also does unpublish actions, created an AbstractEnvironment command. In the feature we could also easly add a publish command.
- You can not unpublish revision from their default environment, you should use revision Archive for this.
- You can not unpublish revision if it's the only environment. This can happen when the revision is archived in the default environment.
=> feat: unpublish command

composer.json, src/Form/Factory/ObjectChoiceListFactory.php, src/Form/Field/ObjectChoiceList.php, src/Form/Field/ObjectChoiceLoader.php, src/Form/Field/ObjectPickerType.php, src/Resources/config/services.yml, src/Service/ObjectChoiceCacheService.php, src/Service/QuerySearchService.php
Solve an error if a datlink field type is using a query search with the dynamic loading not checked
=> fix: load all from querysearch

src/Controller/ElasticsearchController.php
Only when not using QuerySearch, edit link is not showing the label.
ContentType should be added before the document, otherwise we can not resolve the labelField
=> fix: datalinks not showing selected

src/Controller/Revision/EditController.php, src/Form/Form/RevisionType.php, src/Resources/translations/EMSCoreBundle.en.yml, src/Resources/views/elements/revision-toolbar.html.twig
* Edit a revision that is not published in any environments
* Showing a blue submit button"Save and publish in" >  fixed now showing blue "Save" button. Because we will only update the revision in the database.
* Edit archived revision that is published in live environment
* Showing a gray submit button "Save as draft" > fixed now showing blue "Save and publish in Live"
On save we only published if they revision had an endTime, this check could be removed. If we save a revision and it has environments, we should publish.
Creating a draft -> new revision (no environments), so will not conflict with above logic.
=> fix: save/edit publish revision
